### ISSUE TITLE
Failed to activate the atom-ide-go package

### ISSUE THREAD

**Issue by xtgoxa** [stamblerre/atom-ide-go#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-go](https://github.com/stamblerre/atom-ide-go) package 0.1.0

### Stack Trace

Failed to activate the atom-ide-go package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-ide-go/lib/main.js:2:32)
    at /packages/atom-ide-go/lib/main.js:29:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:728962)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3328046)
    at Package.activateNow (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3316030)
    at measure (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3315808)
    at Package.measure (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3313418)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3315668)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:3315611)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:382547)
    at config.transactAsync (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:382163)
    at Config.transactAsync (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:331811)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:382113)
    at PackageManager.activate (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:381663)
    at t.loadState.then (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:751127)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-go 0.1.0 
simplified-chinese-menu 5.3.5 
```

**Comment by stamblerre** [comment]
Instead of this package, I would recommend installing the ide-gopls package as described [here](https://github.com/golang/tools/blob/master/gopls/doc/atom.md). I think you will also need to install the atom-ide-ui package.
